public class Julzzz {
	public static void main(String[] args) {
		int jumlahSiswa = 29;
		System.out.println("Jumlah siswa awal: " + jumlahSiswa);
		jumlahSiswa = 32;
		System.out.println("Jumlah siswa setelah ada tabahan: " + jumlahSiswa);
		final double PI = 3.14159;
		System.out.println("Nilai PI: " + PI);
		String namaKampus = "Unsulbar";
		System.out.println("Nama kampus: " + namaKampus);        final boolean LULUS = true;
		System.out.println("Status kelulusan: " + LULUS);
	}
}
