public class Julzzz {
	public static void main(String[] args) {
		String nama = "zul", pendek = "Jul";
		Byte ma = 20, mi = 30;
		short sa = 200, ya = 100;
		int la = 1000, qa = 2000;
		long ru = 10000, da = 20000;
		char le = 'A', cu = 'B';
		float re = 10.1f, ge = 20.2f;
		double ii = 20.2, is = 10.1;
		boolean gw = true, dia = true;
		System.out.println("Variabel sebelum update: ");
		System.out.println(nama);
	    System.out.println(pendek);
		System.out.println(ma);
		System.out.println(mi);
		System.out.println(sa);
		System.out.println(ya);
		System.out.println(la);
		System.out.println(qa);
		System.out.println(ru);
		System.out.println(da);
		System.out.println(le);
		System.out.println(cu);
		System.out.println(re);
		System.out.println(ge);
		System.out.println(ii);
		System.out.println(is);
		System.out.println(gw);
		System.out.println(dia);
		System.out.printf("re: %. 1f%n ge: %. 1f%n ii: %. 1f%n is: %. 1f%n gw: %b%n dia: %b%n%n", re, ge, ii, is, gw, dia);
		
		
		nama = "Ahyar"; pendek = "isa";
		ma = 20; mi = 30;
		sa = 200; ya = 300;
		la = 2000; qa = 3000;
		ru = 3000; da = 4000;
		le = 'C'; cu = 'D';
		re = 40.1f; ge = 50.2f;
		ii = 90.2; is = 80.1;
		gw = false; dia = false;
		System.out.println("Sesudah update variabel: ");
		System.out.println(nama);
		System.out.println(pendek);
		System.out.println(ma);
		System.out.println(mi);
		System.out.println(sa);
		System.out.println(ya);
		System.out.println(la);
		System.out.println(qa);
		System.out.println(ru);
		System.out.println(da);
		System.out.println(le);
		System.out.println(cu);
		System.out.println(re);
		System.out.println(ge);
		System.out.println(ii);
		System.out.println(is);
		System.out.println(gw);
		System.out.println(dia);
		System.out.printf("re: %. 1f%n ge: %. 1f%n ii: %. 1f%n is: %. 1f%n gw: %b%n dia: %b%n", re, ge, ii, is, gw, dia);
		
	}
}
