public class Main {
    public static void main(String[] args) {
        int x = 16;
        int y = 29;

        System.out.println("x = " + x);
        System.out.println("y = " + y);

        System.out.println("x < y: " + (x < y)); 
        System.out.println("x > y: " + (x > y)); 
        System.out.println("x < 16: " + (x < 16)); 
        System.out.println("x > 16: " + (x > 16)); 
        System.out.println("x < 30: " + (x < 30)); 
        System.out.println("y > 20: " + (y > 20)); 
    }
}
