public class Main {
	public static void main(String[] args) {
		int z = 16;
		System.out.println("Nilai awal z: " + z);
		
		z = 29;
		System.out.println("Nilai z setelah penegasan sederhana: " + z);
		
		z = z + 12;
		System.out.println("Nilai z setelah ditambah: " + z);
		
		z = z - 10;
		System.out.println("Nilai z setelah dikurangi: " + z);
		
		z = z * 8;
		System.out.println("Nilai z setelah dikali: " + z);
		
		z = z / 6;
		System.out.println("Nilai z setelah dibagi: " + z);
	}
}
