public class Main {
	public static void main(String[] args) {
		System.out.println("Nama saya Zul Ahyar Baharuddin");
		System.out.println("Prodi Informatika");
		System.out.println("Umur saya 18 tahun");
		System.out.println();
		System.out.print("Nama saya Zul Ahyar Baharuddin");
		System.out.print("Prodi Informatika");
		System.out.print("Umur saya 18 tahun");
		System.out.println();
		System.out.printf("\nNama saya %s %nUmur %d %nProdi %s ","Zul Ahyar Baharuddin",18,"Informatika");
	}
}
