public class Main {
    public static void main(String[] args) {
        int x = 2;
        int y = 8;

        System.out.println("x = " + x);
        System.out.println("y = " + y);

        System.out.println("x <= y: " + (x <= y)); 
        System.out.println("x >= y: " + (x >= y));
        System.out.println("x <= 5: " + (x <= 5));
        System.out.println("x >= 5: " + (x >= 5));
        System.out.println("x <= 2: " + (x <= 2));
        System.out.println("y >= 5: " + (y >= 5)); 
    }
}
