public class Main {
	public static void main(String[] args) {
	// Digunakan untuk meneruskan argumen baris perintah ke program  java saat digunakan.
		String nama = "Zul";
		String hobi = "Badminton";
		
		// Println digunakan untuk mencetak string literal dengan baris baru.
		System.out.println("Nama Zul");
		System.out.println("Hobi Badminton");
		
		// Print digunakan untuk mencetak string literal tanpaenggukan baris baru.
		System.out.print("Nama Zul");
		System.out.print("Hobi Badminton");
		System.out.print("Nama");
		System.out.print("Hobi");
		
		// Printf digunakan untuk mencetak string yang sudah di format dengan baris baru di awal dan akhir, serta memasukkan nilai string literal kedalam output.
		System.out.printf("\nNama: %s\n", "Zul");
		System.out.printf("\nHobi: %s\n", "Badminton");

		
	}
}
