public class ZulajaD0225007 {
	public static void main(String[] args) {
		String tinggi,umur,status;
		
		double Tinggi = 165;
		int Umur = 18;
		String Status = "Mahasiswa";
		System.out.println("Umur: \t" + 18 + "tahun\n" + "Tinggi: \t" + 165 + " cm\n" + "Status: \t" + Status);
		
		
		// Sequence \n digunakan untuk membuat baris baru mimisahkan taks menjadi baris-baris yang berbeda.
		// Sequence \t digunakan untuk membuat identitas horizontal mensipkan spasi atau meratakan teks.
		
		
		
	}
}
