public class Main {
	public static void main(String[] args) {
		// Tipe data byte
		// byte tipe data bilangan bulat yang paling kecil, bisa digunakan untuk menyimpan angkat yang kecil
		byte nilaiByte = 120;
		System.out.println("Nilai byte: " + nilaiByte);
		// Tipe data short
		// short tipe data bilangan bulat yang lebih besar dari byte,bisa digunakan menyimpan angka yang tdk terlalu besar
		short nilaiShort = 32000;
		System.out.println("Nilai short: " + nilaiShort);
		// Tipe data int
		// int tipe data bilangan bulat yang umum digunakan  cukup beser untuk menyimpan sebagain besar angka yang seeing dipakai dalam program
		int nilaiInt = 1500000;
		System.out.println("Nilai int: " + nilaiInt);
		// Tipe data long
		// long tipe data bilangan yang paling besar.Diguanakan untuk menyimpan angka yang sangat besar
		long nilainLong = 9000000000L;
		System.out.println("Nilai long: " + nilainLong);
		
	}
}
