public class Julzz {
	public static void main(String[] args) {
		String nama_depan = "Zul";
		String nama_belakang = "Ahyar";
		String nama_lengkap = nama_depan + " " + nama_belakang;
		System.out.println("Nama lengkap: + nama_lengkap)" );
		String kata = "python";
		System.out.println("Karakter pertama: " + kata.charAt(0) );
		System.out.println("Substring: " + kata.substring(2, 5) );
		String teks = "Hellow world! ";
		System.out.println("Panjang teks: " + teks.length( ) );
		System.out.println("Teks tanpa spasi: " + teks.trim( ) );
		int umur= 18;
		System.out.println(nama_depan + " berumur " + umur + "tahun. ");
		
	}
}
